repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: cloud-init-schema
        name: Validate cloud-init configs
        language: system
        entry: cloud-init schema --annotate -c
        files: e2e-validator\.cloud-init\.yml$
        types: [yaml]
